"""add auth: password hash, lockout fields, sessions table

Revision ID: 04bec2d073c3
Revises: 3916c4c3d4fd
Create Date: 2026-06-25 13:12:12.094203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04bec2d073c3'
down_revision: Union[str, Sequence[str], None] = '3916c4c3d4fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    # server_default values below only exist to satisfy NOT NULL on any pre-existing
    # rows (dev DB has a seeded user); the placeholder password_hash can never match
    # any real bcrypt verify() call, so it doesn't grant access -- app/seed.py sets a
    # real one immediately after.
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=False, server_default='unset'))
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(), nullable=True))
    op.alter_column('users', 'password_hash', server_default=None)
    op.alter_column('users', 'failed_login_attempts', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('users', 'password_hash')
    op.drop_table('sessions')
    # ### end Alembic commands ###
