"""integration connection type and encrypted config, resize embedding dim

Revision ID: 0ba80d6e031b
Revises: 225d6b0ab71a
Create Date: 2026-06-24 15:04:15.435931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ba80d6e031b'
down_revision: Union[str, Sequence[str], None] = '225d6b0ab71a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('controls', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               existing_nullable=True)
    op.add_column('integration_connections', sa.Column('integration_type', sa.String(), nullable=False))
    op.add_column('integration_connections', sa.Column('config_ciphertext', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'integration_connections', ['organization_id', 'integration_type'])
    op.drop_column('integration_connections', 'config')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integration_connections', sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'integration_connections', type_='unique')
    op.drop_column('integration_connections', 'config_ciphertext')
    op.drop_column('integration_connections', 'integration_type')
    op.alter_column('controls', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=True)
    # ### end Alembic commands ###
